import Collaborate from '@/components/Collaborate/Collaborate'
import CommonGoals from '@/components/CommonGoals/CommonGoals'
import Hero from '@/components/Hero/Hero'
import MemberBenefits from '@/components/MemberBenefits/MemberBenefits'
import MemberRewards from '@/components/MemberRewards/MemberRewards'
import Minting from '@/components/Minting/Minting'
import Head from 'next/head'
import { Fragment } from 'react'

export default function HomePage() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Minting />
      <CommonGoals />
      <MemberBenefits />
      <MemberRewards />
      <Collaborate />
    </Fragment>
  )
}
